### ISSUE TITLE
Meetings

### ISSUE THREAD

**Issue by jonathom** [jonathom/summer_project#7]
- calculate meeting points
- display meeting points
- put meetings into database?

**Comment by DrSherwood** [comment]
+ http://turfjs.org/docs/#lineIntersect  a possible way to calculate the intersections of two linestrings
+ returns the intersected points as points in a GeoJSON FeatureCollection, which can be easily added to the map

**Comment by DrSherwood** [comment]
+ functions for detecting intersections works
+ adding the meeting points also works
+ Next on: 
   +A better way of comparing 2 or more routes
   +Providing context to the markers

**Comment by DrSherwood** [comment]
+ Comparison of all routes works
+ Markers show context in a popup
+ Next on:
   -> "Sharing" of the encounters

**Comment by DrSherwood** [comment]
+ Sharing in form of saving each wanted encounter is done
+ Maybe add previous contextinfo to saved entrys

**Comment by DrSherwood** [comment]
+ Added previous contextinfo to saved entrys
